services:
  - type: web
    name: moneytracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false  
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  - name: moneytracker-db
    databaseName: moneytracker
    user: moneytracker_user
    plan: free